### ISSUE TITLE
exception.getResponse() is not IErrorException

### ISSUE THREAD

**Issue by shahanuliota** [andrechristikan/ack-nestjs-boilerplate-mongoose#220]
[error.http.filter.ts]  

response is not always IErrorException type

so those values were undefined
{
  statusCode: undefined,
  message: undefined,
  errors: undefined,
  data: undefined,
  properties: undefined
}

[Nest] 6383  - 07/17/2022, 2:23:28 PM   ERROR [HealthCheckService] Health Check has failed! {"diskHealth":{"status":"down","message":"Used disk storage exceeded the set threshold"}}
(node:6383) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at I18nService.translateObject (/Users/Shahanul/WebstormProjects/ack-nestjs-boilerplate-mongoose/node_modules/nestjs-i18n/src/services/i18n.service.ts:148:22)
    at I18nService.translate (/Users/Shahanul/WebstormProjects/ack-nestjs-boilerplate-mongoose/node_modules/nestjs-i18n/src/services/i18n.service.ts:72:30)
    at MessageService.setMessage (/Users/Shahanul/WebstormProjects/ack-nestjs-boilerplate-mongoose/src/message/service/message.service.ts:116:26)
    at MessageService.get (/Users/Shahanul/WebstormProjects/ack-nestjs-boilerplate-mongoose/src/message/service/message.service.ts:90:55)
    at ErrorHttpFilter.catch (/Users/Shahanul/WebstormProjects/ack-nestjs-boilerplate-mongoose/src/utils/error/filter/error.http.filter.ts:59:73)
    at ExceptionsHandler.invokeCustomFilters (/Users/Shahanul/WebstormProjects/ack-nestjs-boilerplate-mongoose/node_modules/@nestjs/core/exceptions/exceptions-handler.js:33:26)
    at ExceptionsHandler.next (/Users/Shahanul/WebstormProjects/ack-nestjs-boilerplate-mongoose/node_modules/@nestjs/core/exceptions/exceptions-handler.js:13:18)
    at /Users/Shahanul/WebstormProjects/ack-nestjs-boilerplate-mongoose/node_modules/@nestjs/core/router/router-proxy.js:13:35
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6383) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:6383) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by andrechristikan** [comment]
Got it. Thank you for the report.
This will fixed in the next version

Thank you
