### ISSUE TITLE
500 Internal Server Error '/api/v1/auth/user/info' 

### ISSUE THREAD

**Issue by chopbk** [andrechristikan/ack-nestjs-boilerplate-mongoose#443]
i got error when use api /api/v1/auth/user/info. i think payload didn't have permissions in role field
```
{
  _id: 'e7c230b4-0740-4709-8cd4-1fe6e0072300',
  class: 'UserAuthController',
  function: 'info',
  path: '/api/v1/auth/user/info',
  data: TypeError: Cannot read properties of undefined (reading 'map')
      at Object.transformFn (E:\0.Chopbk\ack-nestjs-boilerplate\src\modules\user\serializations\user.payload.serialization.ts:57:37)
      at E:\0.Chopbk\ack-nestjs-boilerplate\node_modules\src\TransformOperationExecutor.ts:412:24
      at Array.forEach (<anonymous>)
      at TransformOperationExecutor.applyCustomTransformations (E:\0.Chopbk\ack-nestjs-boilerplate\node_modules\src\TransformOperationExecutor.ts:411:15)
      at TransformOperationExecutor.transform (E:\0.Chopbk\ack-nestjs-boilerplate\node_modules\src\TransformOperationExecutor.ts:334:33)
      at ClassTransformer.plainToInstance (E:\0.Chopbk\ack-nestjs-boilerplate\node_modules\src\ClassTransformer.ts:77:21)
      at plainToInstance (E:\0.Chopbk\ack-nestjs-boilerplate\node_modules\src\index.ts:84:27)
      at E:\0.Chopbk\ack-nestjs-boilerplate\src\common\response\interceptors\response.default.interceptor.ts:108:51
      at processTicksAndRejections (node:internal/process/task_queues:96:5),
  level: 'error',
  message: "Cannot read properties of undefined (reading 'map')",
  timestamp: '2023-06-23T09:43:16.929Z'
}
```

**Comment by andrechristikan** [comment]
Ohh that right, i do double serialization in `/info` endpoint.
Thank you notice that. I will fix it in next version.

For temp solution, you can do like this
```ts
// change this
@Response('user.info', { serialization: UserPayloadSerialization })

// to this
@Response('user.info')
```
